### ISSUE TITLE
typo and confusing sentence

### ISSUE THREAD

**Issue by jvandemark** [arcege/ansible-primer#3]
diff --git a/10-playbooks/lesson.md b/10-playbooks/lesson.md
index 23ba747..25665f6 100644
--- a/10-playbooks/lesson.md
+++ b/10-playbooks/lesson.md
@@ -6,7 +6,7 @@ Ansible work.  Playbooks give the what, which, when and where.
 _Playbooks_ are YAML files that contain plays, plays then contain tasks
 or roles.

-_Hosts_ and _Hostgroups_ are Ansible perorms the plays, tasks and roles against.
+_Hosts_ and _Hostgroups_ are what Ansible performs the plays, tasks and roles against.
 Hostnames are arbitrary in the _inventory_, but keeping them different from the
 real hostname can lead to confusion.  Groups allow for not just organizing the
 plays, but also setting variables - one group may use port 8888 while another uses

**Comment by arcege** [comment]
Updated on the main/master branch.
